import type {
  AlertPlan,
  InventoryItem,
  PurchaseCandidate,
  PurchaseHistory,
} from '../pages/inventory/types'

export const purchaseCandidates: PurchaseCandidate[] = [
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    variety: 'Roma',
    category: 'Vegetables',
    lastPrice: 'KSh 120',
    availableQuantity: '23 kg',
  },
  {
    id: 'onions',
    name: 'Onions',
    category: 'Vegetables',
    lastPrice: 'KSh 100',
    availableQuantity: '5 kg',
  },
  {
    id: 'bananas',
    name: 'Bananas',
    variety: 'Sweet',
    category: 'Fruits',
    lastPrice: 'KSh 60',
    availableQuantity: '12 kg',
  },
  {
    id: 'milk',
    name: 'Milk',
    category: 'Dairy',
    lastPrice: 'KSh 45',
    availableQuantity: '0 litres',
  },
]

export const inventoryItems: InventoryItem[] = [
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    variety: 'Roma',
    quantity: '23 kg',
    unitPrice: 'KSh 150/kg',
    category: 'Vegetables',
    status: 'Good',
    addedOn: 'Sep 1, 2024',
    expiresOn: 'Oct 1, 2024',
  },
  {
    id: 'onions',
    name: 'Onions',
    quantity: '5 kg',
    unitPrice: 'KSh 120/kg',
    category: 'Vegetables',
    status: 'Low',
    addedOn: 'Sep 11, 2024',
    expiresOn: 'Sep 28, 2024',
  },
  {
    id: 'milk',
    name: 'Milk',
    quantity: '0 litres',
    unitPrice: 'KSh 60/litre',
    category: 'Dairy',
    status: 'Out',
    addedOn: 'Sep 15, 2024',
    expiresOn: 'Sep 25, 2024',
  },
  {
    id: 'bananas',
    name: 'Bananas',
    variety: 'Sweet',
    quantity: '12 kg',
    unitPrice: 'KSh 80/kg',
    category: 'Fruits',
    status: 'Spoiled',
    addedOn: 'Sep 7, 2024',
    expiresOn: 'Sep 20, 2024',
  },
]

export const alertPlans: AlertPlan[] = [
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    category: 'Vegetables',
    status: 'Good',
    enabled: true,
    reorderThreshold: 10,
    criticalThreshold: 5,
    expiryWarningDays: 2,
  },
  {
    id: 'onions',
    name: 'Onions',
    category: 'Vegetables',
    status: 'Good',
    enabled: true,
    reorderThreshold: 8,
    criticalThreshold: 3,
    expiryWarningDays: 7,
  },
  {
    id: 'milk',
    name: 'Milk',
    category: 'Dairy',
    status: 'Out',
    enabled: false,
    reorderThreshold: 6,
    criticalThreshold: 2,
    expiryWarningDays: 3,
  },
  {
    id: 'bananas',
    name: 'Bananas',
    category: 'Fruits',
    status: 'Low',
    enabled: true,
    reorderThreshold: 15,
    criticalThreshold: 8,
    expiryWarningDays: 3,
  },
]

export const purchaseHistory: PurchaseHistory[] = [
  {
    id: 'PUR-001',
    supplier: 'Mama Joyce Supplies',
    date: 'Oct 1, 2024',
    status: 'Complete',
    total: 'KSh 4,500',
    items: ['Tomatoes (25 kg)', 'Onions (15 kg)'],
  },
  {
    id: 'PUR-002',
    supplier: 'Fresh Mart Ltd',
    date: 'Sep 28, 2024',
    status: 'Complete',
    total: 'KSh 2,400',
    items: ['Milk (20 litres)', 'Bananas (25 kg)'],
  },
  {
    id: 'PUR-003',
    supplier: 'Hajajoro Fresh',
    date: 'Sep 25, 2024',
    status: 'Complete',
    total: 'KSh 1,800',
    items: ['Spinach (30 pieces)'],
  },
]
