"""Add product selection to bonus rules

Revision ID: 75626e99a036
Revises: 7e1398303f13
Create Date: 2025-11-29 23:19:10.674528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75626e99a036'
down_revision: Union[str, Sequence[str], None] = '7e1398303f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpesa_transactions_checkout_request_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_mpesa_receipt'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_transactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('merchant_request_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('checkout_request_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('account_reference', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('response_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('response_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('result_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mpesa_receipt', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('raw_payload', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('mpesa_transactions_ibfk_2')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('mpesa_transactions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_mpesa_transactions_mpesa_receipt'), 'mpesa_transactions', ['mpesa_receipt'], unique=True)
    op.create_index(op.f('ix_mpesa_transactions_id'), 'mpesa_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_checkout_request_id'), 'mpesa_transactions', ['checkout_request_id'], unique=False)
    # ### end Alembic commands ###
