"""restructured spoilage entries table

Revision ID: 921588b49d06
Revises: 
Create Date: 2025-11-07 23:11:36.553168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '921588b49d06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpesa_transactions_checkout_request_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_id'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    op.add_column('inventories', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('inventories', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('inventories', sa.Column('spoilage_quantity', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sale_type', sa.String(length=50), nullable=False))
    op.drop_column('products', 'type')
    op.add_column('sales', sa.Column('reference_no', sa.String(length=64), nullable=True))
    op.add_column('sales', sa.Column('payment_type', sa.String(length=50), nullable=False))
    op.add_column('sales', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_reference_no'), 'sales', ['reference_no'], unique=True)
    op.create_foreign_key(None, 'sales', 'carts', ['cart_id'], ['id'])
    op.add_column('spoilage_entries', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.add_column('spoilage_entries', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('spoilage_entries', sa.Column('quantity', sa.Float(), nullable=False))
    op.add_column('spoilage_entries', sa.Column('reason', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('spoilage_entries_ibfk_1'), 'spoilage_entries', type_='foreignkey')
    op.create_foreign_key(None, 'spoilage_entries', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'spoilage_entries', 'products', ['product_id'], ['id'])
    op.drop_column('spoilage_entries', 'converted_to')
    op.drop_column('spoilage_entries', 'inventory_id')
    op.drop_column('spoilage_entries', 'quantity_spoiled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spoilage_entries', sa.Column('quantity_spoiled', mysql.FLOAT(), nullable=False))
    op.add_column('spoilage_entries', sa.Column('inventory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('spoilage_entries', sa.Column('converted_to', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'spoilage_entries', type_='foreignkey')
    op.drop_constraint(None, 'spoilage_entries', type_='foreignkey')
    op.create_foreign_key(op.f('spoilage_entries_ibfk_1'), 'spoilage_entries', 'inventories', ['inventory_id'], ['id'])
    op.drop_column('spoilage_entries', 'reason')
    op.drop_column('spoilage_entries', 'quantity')
    op.drop_column('spoilage_entries', 'product_id')
    op.drop_column('spoilage_entries', 'vendor_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_reference_no'), table_name='sales')
    op.drop_column('sales', 'cart_id')
    op.drop_column('sales', 'payment_type')
    op.drop_column('sales', 'reference_no')
    op.add_column('products', sa.Column('type', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('products', 'sale_type')
    op.drop_column('inventories', 'spoilage_quantity')
    op.drop_column('inventories', 'last_updated')
    op.drop_column('inventories', 'expiry_date')
    op.create_table('mpesa_transactions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('vendor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('merchant_request_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('checkout_request_id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('account_reference', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('response_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('response_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('result_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('result_desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('mpesa_receipt', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('mpesa_transactions_ibfk_2')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('mpesa_transactions_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_mpesa_transactions_id'), 'mpesa_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_checkout_request_id'), 'mpesa_transactions', ['checkout_request_id'], unique=False)
    # ### end Alembic commands ###
